Refactor and enhance `TaskPluginTrait`
joomla-projects/soc21_website-cronjob pull request #29
Opened 2021-10-09 09:21 UTC by ditsuke

### Summary of Changes
- Adds a standard routine handler.
- Upgrades `enhanceTaskItemForm()` to a complete event handler.
- Renames some methods.
- Improves documentation.
- A new status code.
- Code style improvements.

#### TODO
- [ ] Update task plugins. At the moment they're not compatible with these changes.

### Testing Instructions
--

### Actual result BEFORE applying this Pull Request
--

### Expected result AFTER applying this Pull Request
--

### Documentation Changes Required
--

2021-10-09 11:21 UTC, bembelimen requested changes

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +			return false;
I guess, nothing wrong with not beeing a ```com_scheduler.task```, so it shouldn't be ```false``` but ```true``` (otherwise something above could stop/break?)

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
>  			return false;
Here again I would return ```true```

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +		elseif (!empty($callable) && method_exists($this, $callable))
Please check, if e.g. private methods gives ```true``` in this check, but fail when called two lines below and if ```is_callable``` fix this then?

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +		if (!$isSupported || empty($enhancementFormName))
I know, it's a stupid use case, but if the file is called ```0.xml``` this check would do a false negative. Better use ```strlen```?

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +		$enhancementFormFile = $path . '/forms/' . $enhancementFormName . '.xml';
You can secure "user input paths" via ```Path::check```, to prevent ```../../```

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +		if (!empty($callable) && is_callable($callable))
I'm not sure, if we should allow the developer to call any function existing in the environment. I think we should only allow calling things within the plugin (like you do below and if they want to call functions, they can do it there)

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +		}
I think, this whole check could be a bit improved, there could be exitCodes which are not supported at all.

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +			$exitCode = \call_user_func([$this, $callable]);
Thought about a try/catch if really something goes wrong?

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +	protected function initRoutine(ExecuteTaskEvent $event): void
if you have ```endRoutine``` it should be probably ```startRoutine```?

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
>  	protected $snapshot = [];
TBH, that's just me, but I'm not 100% happy with the naming of this variable and that it is an array (snapshots are for me something I could recover to (e.g. backup) and the array is very fragile)

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
>  <?php
Your trait needs an interface

2021-10-09 11:21 UTC, bembelimen commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
>  		$routineId = $data->taskOption->type ?? $data->type ?? $data['type'] ?? $form->getValue('type') ?? $data['taskOption']->type;
```$data['taskOption']->type``` is always set?

2021-10-09 13:42 UTC, ditsuke commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
>  	protected $snapshot = [];
Good point, I've been thinking for a while to turn it into a `Task\RoutineSnapshot` or similar, or perhaps inject the snapshot from the Task into the routine.

2021-10-09 13:45 UTC, ditsuke commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +		if (!$isSupported || empty($enhancementFormName))
Good idea

2021-10-10 10:04 UTC, ditsuke commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +		elseif (!empty($callable) && method_exists($this, $callable))
Using now reflection to get around visibility and enforce signatures.

2021-10-10 10:04 UTC, ditsuke commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +		$enhancementFormFile = $path . '/forms/' . $enhancementFormName . '.xml';
done

2021-10-10 10:04 UTC, ditsuke commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +			$exitCode = \call_user_func([$this, $callable]);
done!

2021-10-10 10:07 UTC, ditsuke commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +		if (!empty($callable) && is_callable($callable))
Thanks. Done with [`c521a5b` (#29)](https://github.com/joomla-projects/soc21_website-cronjob/pull/29/commits/c521a5ba4551c6b67d1b9be2e03c1ae22e261ff5)

2021-10-10 10:07 UTC, ditsuke commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +		}
We check against `Task\Status` now with [`c521a5b` (#29)](https://github.com/joomla-projects/soc21_website-cronjob/pull/29/commits/c521a5ba4551c6b67d1b9be2e03c1ae22e261ff5)

2021-10-10 10:07 UTC, ditsuke commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +	protected function initRoutine(ExecuteTaskEvent $event): void
done

2021-10-21 19:56 UTC, merged